language: node_js
node_js:
  - "7"

install:
  - npm install -g codecov
  

cache:
  directories:
    - "./src/node_modules"
    - $(npm config get prefix)/lib/node_modules
  
before_script:
  - sed -i 's/\[ "node" \]/\[\]/g' "./src/ts/tsconfig.json" # For correcting Error TS2688
  - cd src
  - npm install

script:
  - ./genparser.sh
  - ./build.sh 0
  - ./test.sh 0

after_script:
  - ./node_modules/jest/bin/jest.js --coverage
  - codecov