site_name: Pineapple Doc
nav:
    - Home: index.md
    - About: about.md
    - Features:
        - Basic Functions: features/BasicFunctions.md
        - Advance Functions: features/404.md
theme: readthedocs